on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  - name: Run JSON Lint
    run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
